FORMAT: 1A
HOST: http://api.cw-backend.blur.tech

# Интернет-магазин игр

Серверная часть курсовой работы по дисциплине Технологии Программирования 4 семестра 2 курса.

### Игры [/games]

### Получить список всех игр [GET]
Возвращает всех пользователей массивом объектов

+ Response 200 (application/json)

        {"data":[{"download_link":{"linux":null,"macOS":null,"windows":"/files/witcher3.txt"},"photo":"/images/witcher3.png","thematics":["Открытый мир","Ролевая игра","Глубокий сюжет"],"genre":"Ролевая","online":null,"_id":"5cd52869fec3f9b504179f90","name":"The Witcher® 3: Wild Hunt","price":1119,"description":"Когда в Северных королевствах бушует война, вы заключаете величайший контракт своей жизни — отыскать Дитя предназначения, живое оружие, которое может изменить облик мира."},{"download_link":{"linux":null,"macOS":null,"windows":"/files/witcher2.txt"},"photo":"/images/witcher2.png","thematics":["Открытый мир","Ролевая игра","Глубокий сюжет"],"genre":"Ролевая","online":null,"_id":"5ce56188fec3f9b50404c5d0","name":"The Witcher® 2: Assassins of Kings","price":1119,"description":"Пришло время невиданного хаоса. Могущественные силы сталкиваются в борьбе за власть и величие. Северные королевства готовятся к войне. Но даже армии не могут помешать этому заговору, и прольётся кровь…"}]}

### Получить игру по id [GET/{id}]
Возвращает игру по id

+ Parameters
    + id (string, required) - id игры

+ Response 200 (application/json)

        {"data":{"download_link":{"linux":null,"macOS":null,"windows":"/files/witcher3.txt"},"photo":"/images/witcher3.png","thematics":["Открытый мир","Ролевая игра","Глубокий сюжет"],"genre":"Ролевая","online":null,"_id":"5cd52869fec3f9b504179f90","name":"The Witcher® 3: Wild Hunt","price":1119,"description":"Когда в Северных королевствах бушует война, вы заключаете величайший контракт своей жизни — отыскать Дитя предназначения, живое оружие, которое может изменить облик мира."}}

### Купить игру [POST/buy/{id}]
Совершается покупка игры. Списание со счёта цены игры. Проверка куплена ли игра ранее.

+ Parameters
    + id (string, required) - id игры

+ Request 200 (application/json)

        {
            "_id": "5cf50bda42515b00177e830a"
        }

+ Response 200 (application/json)

        {
            "message": "Game has been purchased",
            "data": {
                "balance": 48881,
                "library": [
                    "5cd52869fec3f9b504179f90"
                ],
                "isAdmin": false,
                "_id": "5cf50bda42515b00177e830a",
                "login": "SrgGrch",
                "password": "1234"
            }
        }

+ Response 400 (application/json)

        {
            "message": "User or game Id is empty"
        }

+ Response 402 (application/json)

        {
            "message": "Not enough money"
        }

+ Response 409 (application/json)

        {
            "message": "The game was purchased earlier"
        }



### Пользователи [/users]

### Получить пользователя по id [GET/{id}]
Возвращает всех пользователей массивом объектов

+ Parameters
    + id (string, required) - id пользователя

+ Response 200 (application/json)

        {
            "data": {
                    "_id":"5cf3f18dc0d594001713cd04",
                    "login":"1",
                    "password":"1",
                    "balance":0,
                    "library": [
                                {
                                                "download_link": {
                                                    "linux": null,
                                                    "macOS": null,
                                                    "windows": "/files/witcher3.txt"
                                                },
                                                "photo": "/images/witcher3.png",
                                                "thematics": [
                                                    "Открытый мир",
                                                    "Ролевая игра",
                                                    "Глубокий сюжет"
                                                ],
                                                "genre": "Ролевая",
                                                "online": null,
                                                "_id": "5cd52869fec3f9b504179f90",
                                                "name": "The Witcher® 3: Wild Hunt",
                                                "price": 1119,
                                                "description": "Когда в Северных королевствах бушует война, вы заключаете величайший контракт своей жизни — отыскать Дитя предназначения, живое оружие, которое может изменить облик мира."
                                            }
                    ],
                    "isAdmin":false
                 }
        }

### Авторизация [POST/auth]
Принимает на вход логин и пароль, если логин и пароль верны возвращает данные пользователя

+ Request 200 (application/json)

        {
            "login": "1",
            "password": "1"
        }

+ Response 200 (application/json)

        {
            "data": {
                    "_id":"5cf3f18dc0d594001713cd04",
                    "login":"1",
                    "password":"1",
                    "balance":0,
                    "library": [
                                "5cd52869fec3f9b504179f90"
                    ],
                    "isAdmin":false
                 }
        }

### Регистрация [POST/reg]
Принимает на вход логин и пароль и если пользователя с таким логином не существует, то регистрирует его

+ Request 200 (application/json)

        {
            "login": "test",
            "password": "test"
        }

+ Response 200 (application/json)

        {
            "data": {
                    "_id": "5cf6613d139ddc5454e330ce",
                    "login": "test",
                    "password": "test",
                    "balance": 0,
                    "library": [],
                    "isAdmin": false
                 }
        }

+ Response 409 (application/json)

        {
            "message": "Error",
            "data": null
        }

### Библиотека пользователя [GET/library/{id}]
Возвращает массив купленных пользователем игр

+ Parameters
    + id (string, required) - id пользователя

+ Response 200 (application/json)

        {
            "data": {
                    "library": [
                                {
                                                "download_link": {
                                                    "linux": null,
                                                    "macOS": null,
                                                    "windows": "/files/witcher3.txt"
                                                },
                                                "photo": "/images/witcher3.png",
                                                "thematics": [
                                                    "Открытый мир",
                                                    "Ролевая игра",
                                                    "Глубокий сюжет"
                                                ],
                                                "genre": "Ролевая",
                                                "online": null,
                                                "_id": "5cd52869fec3f9b504179f90",
                                                "name": "The Witcher® 3: Wild Hunt",
                                                "price": 1119,
                                                "description": "Когда в Северных королевствах бушует война, вы заключаете величайший контракт своей жизни — отыскать Дитя предназначения, живое оружие, которое может изменить облик мира."
                                            }
                               ]
                  }
        }
