FORMAT: 1A
HOST: http://api.cw-backend.blur.tech

# Интернет-магазин игр

Серверная часть курсовой работы по дисциплине Технологии Программирования 4 семестра 2 курса.

### Игры [/games]

### Получить список всех игр [GET]
Возвращает всех пользователей массивом объектов

+ Response 200 (application/json)

        {"data":[{"download_link":{"linux":null,"macOS":null,"windows":"/files/witcher3.txt"},"photo":"/images/witcher3.png","thematics":["Открытый мир","Ролевая игра","Глубокий сюжет"],"genre":"Ролевая","online":null,"_id":"5cd52869fec3f9b504179f90","name":"The Witcher® 3: Wild Hunt","price":1119,"description":"Когда в Северных королевствах бушует война, вы заключаете величайший контракт своей жизни — отыскать Дитя предназначения, живое оружие, которое может изменить облик мира."},{"download_link":{"linux":null,"macOS":null,"windows":"/files/witcher2.txt"},"photo":"/images/witcher2.png","thematics":["Открытый мир","Ролевая игра","Глубокий сюжет"],"genre":"Ролевая","online":null,"_id":"5ce56188fec3f9b50404c5d0","name":"The Witcher® 2: Assassins of Kings","price":1119,"description":"Пришло время невиданного хаоса. Могущественные силы сталкиваются в борьбе за власть и величие. Северные королевства готовятся к войне. Но даже армии не могут помешать этому заговору, и прольётся кровь…"}]}

### Поиск и фильтрация [GET/games/search?{q}&{online}&{genres}&{thematics}]
Возвращает массив объектов игр по параметрам. Значения в параметрах q и online возвращают только те игры, которые подходят под эти параметры. Значения в параметрах genres и thematics возвращают все игры, где есть хоть один из этих параметров. Online на стороне бэкэнда тернарник, любое значение кроме true кастует к false.

+ Parameters
    + q (string) - поисковой запрос
    + online (string) - true если нужно вывести онлайн игры, false если оффлайн игры
    + genres (string) - перечисление через запятую необходимых жанров, можно указать один, можно несколько
    + thematics (string) - перечисление через запятую тематик, можно указать одну, можно несколько

+ Response 404 (application/json)

        {
            "message": "Games not found"
        }

+ Response 200 (application/json)

        {
            "data": [
                {
                    "download_link": {
                        "linux": null,
                        "macOS": null,
                        "windows": "/files/witcher3.txt"
                    },
                    "photo": "/images/witcher3.png",
                    "thematics": [
                        "Открытый мир",
                        "Ролевая игра",
                        "Глубокий сюжет"
                    ],
                    "genre": "Ролевая",
                    "online": null,
                    "_id": "5cd52869fec3f9b504179f90",
                    "name": "The Witcher® 3: Wild Hunt",
                    "price": 1119,
                    "description": "Когда в Северных королевствах бушует война, вы заключаете величайший контракт своей жизни — отыскать Дитя предназначения, живое оружие, которое может изменить облик мира."
                },
                {
                    "download_link": {
                        "linux": null,
                        "macOS": null,
                        "windows": "/files/witcher2.txt"
                    },
                    "photo": "/images/witcher2.png",
                    "thematics": [
                        "Открытый мир",
                        "Ролевая игра",
                        "Глубокий сюжет"
                    ],
                    "genre": "Ролевая",
                    "online": null,
                    "_id": "5ce56188fec3f9b50404c5d0",
                    "name": "The Witcher® 2: Assassins of Kings",
                    "price": 1119,
                    "description": "Пришло время невиданного хаоса. Могущественные силы сталкиваются в борьбе за власть и величие. Северные королевства готовятся к войне. Но даже армии не могут помешать этому заговору, и прольётся кровь…"
                }
            ]
        }

### Получить игру по id [GET/games/{id}]
Возвращает игру по id

+ Parameters
    + id (string, required) - id игры

+ Response 200 (application/json)

        {"data":{"download_link":{"linux":null,"macOS":null,"windows":"/files/witcher3.txt"},"photo":"/images/witcher3.png","thematics":["Открытый мир","Ролевая игра","Глубокий сюжет"],"genre":"Ролевая","online":null,"_id":"5cd52869fec3f9b504179f90","name":"The Witcher® 3: Wild Hunt","price":1119,"description":"Когда в Северных королевствах бушует война, вы заключаете величайший контракт своей жизни — отыскать Дитя предназначения, живое оружие, которое может изменить облик мира."}}

### Добавление игры [POST/games/new]
Добавляется новая игра.

+ Request 200 (application/json)

        {
                                     "thematics": [
                                                "Открытый мир",
                                                "Ролевая игра",
                                                "Глубокий сюжет"
                                     ],
                                     "genre": "Ролевая",
                                     "name": "Тест",
                                     "price": 100,
                                     "description": "Тест"
        }

+ Response 200 (application/json)

                {
                    "data": {
                             "download_link": null,
                             "photo": "/images/nophoto.png",
                             "thematics": [
                                        "Открытый мир",
                                        "Ролевая игра",
                                        "Глубокий сюжет"
                             ],
                             "genre": "Ролевая",
                             "online": null,
                             "_id": "5ce56188fec3f9b50404c5d5",
                             "name": "Тест",
                             "price": 100,
                             "description": "Тест"
                             }
                }

### Изменение игры [POST/games/new/{id}]
Изменение данных игры

+ Request 200 (application/json)

        {
        	"name": "Test name 1",
              "price": 150,
              "description": "Test description 1",
              "thematics": ["Test", "Failed"]
        }

+ Response 200 (application/json)

                {
                    "data": {
                        "download_link": {
                            "linux": null,
                            "macOS": null,
                            "windows": null
                        },
                        "photo": "/images/nophoto.png",
                        "thematics": [
                            "Test",
                            "Failed"
                        ],
                        "genre": null,
                        "online": null,
                        "_id": "5cf9833cedf9d937bc957f2a",
                        "name": "Test name 1",
                        "price": 150,
                        "description": "Test description 1"
                    }
                }

### Купить игру [POST/games/buy/]
Совершается покупка игры. Списание со счёта цены игры. Проверка куплена ли игра ранее.

+ Request 200 (application/json)

        {
            "userId": "5cf50bda42515b00177e830a",
            "gameId": "5cd52869fec3f9b504179f90"
        }

+ Response 200 (application/json)

        {
            "message": "Game has been purchased",
            "data": {
                "balance": 48881,
                "library": [
                    "5cd52869fec3f9b504179f90"
                ],
                "isAdmin": false,
                "_id": "5cf50bda42515b00177e830a",
                "login": "SrgGrch",
                "password": "1234"
            }
        }

+ Response 400 (application/json)

        {
            "message": "User or game Id is empty"
        }

+ Response 402 (application/json)

        {
            "message": "Not enough money"
        }

+ Response 404 (application/json)

        {
            "message": "Game not found"
        }

+ Response 404 (application/json)

        {
            "message": "User not found"
        }

+ Response 409 (application/json)

        {
            "message": "The game was purchased earlier"
        }



### Пользователи [/users]

### Получить пользователя по id [GET/users/{id}]
Возвращает всех пользователей массивом объектов

+ Parameters
    + id (string, required) - id пользователя

+ Response 200 (application/json)

        {
            "data": {
                    "_id":"5cf3f18dc0d594001713cd04",
                    "login":"1",
                    "password":"1",
                    "balance":0,
                    "library": [
                                {
                                                "download_link": {
                                                    "linux": null,
                                                    "macOS": null,
                                                    "windows": "/files/witcher3.txt"
                                                },
                                                "photo": "/images/witcher3.png",
                                                "thematics": [
                                                    "Открытый мир",
                                                    "Ролевая игра",
                                                    "Глубокий сюжет"
                                                ],
                                                "genre": "Ролевая",
                                                "online": null,
                                                "_id": "5cd52869fec3f9b504179f90",
                                                "name": "The Witcher® 3: Wild Hunt",
                                                "price": 1119,
                                                "description": "Когда в Северных королевствах бушует война, вы заключаете величайший контракт своей жизни — отыскать Дитя предназначения, живое оружие, которое может изменить облик мира."
                                            }
                    ],
                    "isAdmin":false
                 }
        }

### Авторизация [POST/users/auth]
Принимает на вход логин и пароль, если логин и пароль верны возвращает данные пользователя

+ Request 200 (application/json)

         {
            "login": "1",
            "password": "1"
         }

+ Response 200 (application/json)

         {
                     "data": {
                             "_id":"5cf3f18dc0d594001713cd04",
                             "login":"1",
                             "password":"1",
                             "balance":0,
                             "library": [
                                         "5cd52869fec3f9b504179f90"
                             ],
                             "isAdmin":false
                          }
         }

### Пополенение баланса [POST/users/refill]
Принимает на вход id пользователя и сумму пополенения. Поля не должны быть пустыми, а сумма пополнения должна быть неотрицательной.

+ Request 200 (application/json)

        {
        	"userId": "5cf3f18dc0d594001713cd04",
        	"amount": 100
        }

+ Response 400 (application/json)

        {
            "message": "Amount or userId is empty"
        }

+ Response 403 (application/json)

        {
            "message": "Wrong refill amount"
        }

+ Response 404 (application/json)

        {
            "message": "User not found"
        }

+ Response 200 (application/json)

        {
            "data": {
                "balance": 300,
                "library": [
                    "5cd52869fec3f9b504179f90"
                ],
                "isAdmin": false,
                "_id": "5cf3f18dc0d594001713cd04",
                "login": "1",
                "password": "1"
            }
        }

### Регистрация [POST/users/reg]
Принимает на вход логин и пароль и если пользователя с таким логином не существует, то регистрирует его

+ Request 200 (application/json)

        {
            "login": "test",
            "password": "test"
        }

+ Response 200 (application/json)

        {
            "data": {
                    "_id": "5cf6613d139ddc5454e330ce",
                    "login": "test",
                    "password": "test",
                    "balance": 0,
                    "library": [],
                    "isAdmin": false
                 }
        }

+ Response 409 (application/json)

        {
            "message": "Error",
            "data": null
        }

### Библиотека пользователя [GET/users/library/{id}]
Возвращает массив купленных пользователем игр

+ Parameters
    + id (string, required) - id пользователя

+ Response 200 (application/json)

        {
            "data": {
                    "library": [
                                {
                                                "download_link": {
                                                    "linux": null,
                                                    "macOS": null,
                                                    "windows": "/files/witcher3.txt"
                                                },
                                                "photo": "/images/witcher3.png",
                                                "thematics": [
                                                    "Открытый мир",
                                                    "Ролевая игра",
                                                    "Глубокий сюжет"
                                                ],
                                                "genre": "Ролевая",
                                                "online": null,
                                                "_id": "5cd52869fec3f9b504179f90",
                                                "name": "The Witcher® 3: Wild Hunt",
                                                "price": 1119,
                                                "description": "Когда в Северных королевствах бушует война, вы заключаете величайший контракт своей жизни — отыскать Дитя предназначения, живое оружие, которое может изменить облик мира."
                                            }
                               ]
                  }
        }
